spring:
    application:
        name: iot-vmp-vmanager
        # 影子数据存储方式，支持redis、jdbc
        database: redis
        # 通信方式，支持kafka、http
        communicate: http
    redis: 
        # Redis服务器IP
        #host: 10.24.20.63
        host: 127.0.0.1
        #端口号
        port: 6379
        datebase: 0
        #访问密码,若你的redis服务器没有设置密码，就不需要用密码去连接
        password:
        #超时时间
        timeout: 10000
    datasource: 
        name: eiot
        url: jdbc:mysql://10.24.20.63:3306/eiot?useUnicode=true&characterEncoding=UTF8&rewriteBatchedStatements=true
        username: root
        password: 123456
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
server:
    port: 8080
sip:
    ip: 10.200.64.63
    port: 5060
    # 根据国标6.1.2中规定，domain宜采用ID统一编码的前十位编码。国标附录D中定义前8位为中心编码（由省级、市级、区级、基层编号组成，参照GB/T 2260-2007）
    # 后两位为行业编码，定义参照附录D.3
    # 3701020049标识山东济南历下区 信息行业接入
    domain: 3701020049
    server_id: 37010200492000000001
    # 默认设备认证密码，后续扩展使用设备单独密码
    password: admin
media:
    ip: 10.200.64.88
    port: 10000