spring:
    # 上传文件大小限制
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 100MB
    # REDIS数据库配置
    redis:
        # [必须修改] Redis服务器IP, REDIS安装在本机的,使用127.0.0.1
        host: ${REDIS_HOST:127.0.0.1}
        # [必须修改] 端口号
        port: ${REDIS_PORT:6379}
        # [可选] 数据库 DB
        database: ${REDIS_DB:6}
        # [可选] 访问密码,若你的redis服务器没有设置密码，就不需要用密码去连接
        password: ${REDIS_PWD:root}
        # [可选] 超时时间
        timeout: 10000
    # [可选] jdbc数据库配置, 项目使用sqlite作为数据库，一般不需要配置
    datasource:
        # 使用mysql 打开23-28行注释， 删除29-36行
         name: wvp
         url: jdbc:mysql://127.0.0.1:3306/wvp?useUnicode=true&characterEncoding=UTF8&rewriteBatchedStatements=true&allowMultiQueries=true&useSSL=false
         username: root
         password: root
         type: com.alibaba.druid.pool.DruidDataSource
         driver-class-name: com.mysql.cj.jdbc.Driver

# [可选] WVP监听的HTTP端口, 网页和接口调用都是这个端口
server:
    port: 18080

# 作为28181服务器的配置
sip:
    # [必须修改] 本机的IP
    ip: ${WVP_HOST:127.0.0.1}
    # [可选] 28181服务监听的端口
    port: ${WVP_PORT:5060}
    # 根据国标6.1.2中规定，domain宜采用ID统一编码的前十位编码。国标附录D中定义前8位为中心编码（由省级、市级、区级、基层编号组成，参照GB/T 2260-2007）
    # 后两位为行业编码，定义参照附录D.3
    # 3701020049标识山东济南历下区 信息行业接入
    # [可选]
    domain: ${WVP_DOMAIN:4401020049}
    # [可选]
    id: ${WVP_ID:44010200492000000001}
    # [可选] 默认设备认证密码，后续扩展使用设备单独密码, 移除密码将不进行校验
    password: ${WVP_PWD:admin123}

#zlm 默认服务器配置
media:
    # [必须修改] zlm服务器唯一id，用于触发hook时区别是哪台服务器,general.mediaServerId
    id:
    # [必须修改] zlm服务器的内网IP
    ip: ${ZLM_HOST:127.0.0.1}
    # [必须修改] zlm服务器的http.port
    http-port: ${ZLM_PORT:80}
    # [可选] zlm服务器的hook.admin_params=secret
    secret: 035c73f7-bb6b-4889-a715-d9eb2d1925cc
    # 启用多端口模式, 多端口模式使用端口区分每路流，兼容性更好。 单端口使用流的ssrc区分， 点播超时建议使用多端口测试
    rtp:
        # [可选] 是否启用多端口模式, 开启后会在portRange范围内选择端口用于媒体流传输
        enable: true
        # [可选] 在此范围内选择端口用于媒体流传输,
        port-range: 30000,30500 # 端口范围
        # [可选] 国标级联在此范围内选择端口发送媒体流,
        send-port-range: 30000,30500 # 端口范围
    # 录像辅助服务， 部署此服务可以实现zlm录像的管理与下载， 0 表示不使用
    record-assist-port: 18081
    sdp-ip: ${sip.ip}
    stream-ip: ${sip.ip}
# [可选] 日志配置, 一般不需要改
# [可选] 日志配置, 一般不需要改
logging:
    config: classpath:logback-spring-local.xml

# [根据业务需求配置]
user-settings:
    # 推流直播是否录制
    record-push-live: true
    auto-apply-play: true

# 在线文档： swagger-ui（生产环境建议关闭）
swagger-ui:
    enabled: true

# 版本信息， 不需修改
version:
    version: "@project.version@"
    description: "@project.description@"
    artifact-id: "@project.artifactId@"
